### ISSUE TITLE
rows ignored?

### ISSUE THREAD

**Issue by toby78** [Indoqa/solr-spatial-clustering#4]
The size of the pins seems to be globally?

e.g. if result is narrowed down by rows parameter, the sizes of the pins dont change?

**Comment by mepheser** [comment]
@toby78 The pins work like facets, they always represent the clusters based on the *whole* result, meaning all possible result documents. So it even works with rows=0. The plugin is designed like that on purpose. The idea is to keep the data retrieval and transportation as efficient as possible, even for larger result sets.
