### ISSUE TITLE
Wrong order of parameters

### ISSUE THREAD

**Issue by son-of-liberty** [Indoqa/solr-spatial-clustering#6]
https://github.com/Indoqa/solr-spatial-clustering/blob/4273bd103e26a351fed3e8c4ef9215774ce007a3/src/main/java/com/indoqa/solr/spatial/clustering/SpatialClusteringComponent.java#L135

Please can you switch the parameter here. Otherwise latitude and longitude will be switched

**Comment by stevendolg** [comment]
Hello,

Longitude and latitude were indeed swapped in the result.
The issue has been fixed and a unit test for it was added as well.

Very well spotted and thank you for reporting!
