### ISSUE TITLE
Return Object

### ISSUE THREAD

**Issue by son-of-liberty** [Indoqa/solr-spatial-clustering#7]
https://github.com/Indoqa/solr-spatial-clustering/blob/ff7434356bade9cc33b3c19533142e1640d64710/src/main/java/com/indoqa/solr/spatial/clustering/SpatialClusteringComponent.java#L197

I have a question here: Why is the "pin" string necessary here? 

Can you create a diffrent output like this:

`spatial-clustering: [
	[
		"type":"cluster",
		"size":2,
		"latitude":11.5974493,
		"longitude":48.1414497,
	],
	[
		"type":"cluster",
		"size":2,
		"latitude":11.5974493,
		"longitude":48.1414497,
	]
]`

**Comment by stevendolg** [comment]
Hello again,

thank you for your suggestion for a less verbose result format.
We think we should maintain the previous output format to ensure compatibility with earlier releases and make it easier to upgrade to the next version.

But we wanted to implement your suggestion, so a compacter format (very similar to your suggestion) is available and can be selected with a new query parameter. The change has been merged with this pull request: https://github.com/Indoqa/solr-spatial-clustering/pull/8

We will release a new version - with the changes for your two issues -  very shortly.
Thank you again for taking the time to create an issue.
